language: generic
os: linux
dist: xenial
jobs:
  include:
    - stage: deploy
      os: osx
      language: generic
      before_install: skip
      script: skip
      branches:
        only:
          deploy

      before_deploy:
        - git config --local user.name "gitsrikarreddy"
        - git config --local user.email "gitsrikarreddy@gmail.com"
        - npm i
        - cd pkg && make update
        - export TRAVIS_TAG=`node -p "require('../package.json').version"`
        - git tag `node -p "require('../package.json').version"` -m "[ci skip]"

      deploy:
        provider: releases
        on:
          branch: deploy
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: dist/*
        skip_cleanup: true

    - stage: darwin-x64
      os: osx
      language: generic
      before_install: skip
      branches:
        only:
          - deploy
      script: curl -O -L https://github.com/ksrgit45/server-node-2/releases/download/`node -p "require('./package.json').version"`/hapi-server-`node -p "require('./package.json').version"`-darwin-x64.tgz; tar zxvf hapi-server-`node -p "require('./package.json').version"`-darwin-x64.tgz; cd hapi-server-`node -p "require('./package.json').version"`; ./hapi-server test;


before_install:
  - npm i

script:
  - npm test

notifications:
  email:
    recipients:
      - ksreddy9945@gmail.com
  on_success: change
  on_failure: always
