language: generic
os: linux
dist: xenial

jobs:
  include:
    - os: linux
      language: node_js
      node_js: "6.16"
      branches:
         only: master

    - os: windows
      language: node_js
      node_js: "8.11.3"
      branches:
        only: master

    - os: osx
      language: node_js
      node_js: "6.16"
      branches:
        only: master

    - stage: deploy
      os: osx
      language: generic
      before_install: skip
      script: skip

      branches:
        only:
          deploy

      before_deploy:
        - git config --local user.name "gitsrikarreddy"
        - git config --local user.email "gitsrikarreddy@gmail.com"
        - cd pkg && make update VERSION=`node -p "require('../package.json').version"`
        - export TRAVIS_TAG=`node -p "require('../package.json').version"`
        - git tag `node -p "require('../package.json').version"` -m "[skip travis]"

      deploy:
        provider: releases
        on:
          branch: releases
        token: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: dist/*
    - stage: test-osx
      os: osx
      language: generic
      before_install: skip
      branches:
        only:
          - deploy
      script: curl -O http://github/hapi-server-osx-`node -p "require('../package.json').version"`.tgz; tar xvf hapi-server-osx-`node -p "require('../package.json').version"`.tgz; cd hapi-server-osx; ../hapi-server test
    - stage: test-linux
      os: linux
      language: generic
      before_install: skip

      branches:
        only:
          - deploy
      script: curl -O http://github/hapi-server-linux-`node -p "require('../package.json').version"`.tgz; tar xvf hapi-server-linux-`node -p "require('../package.json').version"`.tgz; cd hapi-server-linux; ../hapi-server test

before_install:
  - npm i

script:
  - npm test

notifications:
  email:
    recipients:
      - ksreddy9945@gmail.com
  on_success: change
  on_failure: always
