sudo: required
os:
  - linux
  - osx
language: node_js
node_js:
  - "6.16"
before_install:
  - npm  i
script:
  - node test/server-test.js -- --coverage
  - node test/subset-test.js -- --coverage
notifications:
  if branch = master:
    email:
      recipients:
        - rweigel@gmu.edu
        - ksreddy9945@gmail.com
    on_success: change
    on_failure: always