language: generic
####Commit11
before_deploy:
  - git config --local user.name "srikargitreddy"
  - git config --local user.email "srikarreddygit@gmail.com"
  - npm verison patch -no-git-tag-version
  - cd pkg && make update VERSION=`node -p "require('../package.json').version"`
  - export TRAVIS_TAG=`node -p "require('./package.json').version"`
  - git tag `node -p "require('../package.json').version"`
  - pwd

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: pkg/**/*
  skip_cleanup: true

after_deploy:
  - echo $TRAVIS_TAG
