language: generic

before_deploy:
  - git config --local user.name "srikargitreddy"
  - git config --local user.email "srikarreddygit@gmail.com"
  - npm verison patch -no-git-tag-version
  - export TRAVIS_TAG=`node -p "require('./package.json').version"`
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true

after_deploy:
  - echo $TRAVIS_TAG
