sudo: required
jobs:
  include:
    - os: osx
      language: node_js
      node_js:
        - "6.16"


before_install:
  - npm i

script:
#  - npm test
  - git config --local user.name "rweigel"
  - git config --local user.email "rweigel@gmu.edu"
  - export GITHUB_TOKEN=$GITHUB_OAUTH_TOKEN
  - git checkout release; git merge master
  - cd pkg; make release GITHUB_OAUTH_TOKEN=$(GITHUB_OAUTH_TOKEN)

# Trigger build only for these branches
branches:
  only:
  - master

notifications:
  email:
    recipients:
      - rweigel@gmu.edu
      - ksreddy9945@gmail.com
  on_success: change
  on_failure: always