language: generic
os: linux
dist: xenial
jobs:
  include:
    - os: linux
      language: node_js
      node_js: "6.16"
      branches:
         only: master

    - os: windows
      language: node_js
      node_js: "8.11.3"
      branches:
        only: master

    - os: osx
      language: node_js
      node_js: "6.16"
      branches:
        only: master

    - stage: deploy
      os: osx
      language: generic
      before_install: skip
      script: skip
      branches:
        only:
          deploy

      before_deploy:
        - git config --local user.name "gitsrikarreddy"
        - git config --local user.email "gitsrikarreddy@gmail.com"
        - cd pkg && make update
        - export TRAVIS_TAG=`node -p "require('../package.json').version"`
        - git tag `node -p "require('../package.json').version"`

      deploy:
        provider: releases
        on:
          branch: deploy
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: dist/*
        skip_cleanup: true

    - stage: darwin-x64
      os: osx
      language: generic
      before_install: skip
      branches:
        only:
          - deploy
      script: curl -O https://github.com/ksrgit45/server-node-1/releases/download/`node -p "require('./package.json').version"`/hapi-server-`node -p "require('./package.json').version"`-darwin-x64.tgz; tar zxvf hapi-server-`node -p "require('./package.json').version"`-darwin-x64.tgz; cd hapi-server-`node -p "require('./package.json').version"`; ./hapi-server test
    - stage: linux-armv7l
      os: linux
      language: generic
      before_install: skip
      branches:
        only:
          - deploy
      script: curl -O https://github.com/ksrgit45/server-node-1/releases/download/`node -p "require('./package.json').version"`/hapi-server-`node -p "require('./package.json').version"`-linux-armv7l.tgz; tar zxvf hapi-server-`node -p "require('./package.json').version"`-linux-armv7l.tgz; cd hapi-server-`node -p "require('./package.json').version"`; ./hapi-server test

    - stage: linux-x64
      os: linux
      language: generic
      before_install: skip
      branches:
        only:
          - deploy
      script: curl -O https://github.com/ksrgit45/server-node-1/releases/download/`node -p "require('./package.json').version"`/hapi-server-`node -p "require('./package.json').version"`-linux-x64.tgz; tar zxvf hapi-server-`node -p "require('./package.json').version"`-linux-x64.tgz; cd hapi-server-`node -p "require('./package.json').version"`; ./hapi-server test

before_install:
  - npm i

script:
  - npm test

notifications:
  email:
    recipients:
      - ksreddy9945@gmail.com
  on_success: change
  on_failure: always
