sudo: required
os:
  - linux
  - osx
language: node_js
node_js:
  - "6.16"
before_install:
  - npm  i
script:
  - npm run-script test-https -- --coverage
  - node test/server-test.js -- --coverage
  - node test/subset-test.js -- --coverage
