language: generic
os: linux
dist: xenial
env:
  global:
    - npm_ver=`node -p "require('./package.json').version"`
jobs:
  include:
    - stage: deploy
      os: osx
      language: generic
      before_install: skip
      script: skip
      branches:
        only:
          deploy

      before_deploy:
        - git config --local user.name "gitgitksr"
        - git config --local user.email "gitgitksr@gmail.com"
        - npm i
        - cd pkg && make update
        - export TRAVIS_TAG=$npm_ver
        - git tag $npm_ver

      deploy:
        provider: releases
        on:
          branch: deploy
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: dist/*
        skip_cleanup: true

    - stage: win-x64
      os: windows
      before_install: skip
      branches:
        only:
          - deploy
      script: curl -O -L https://github.com/gitgitksr/server-node-3/releases/download/$npm_ver/hapi-server-$npm_ver-win-x64.tgz; tar zxvf hapi-server-$npm_ver-win-x64.tgz; cd hapi-server-$npm_ver; .\\bin\node test\hapi-server.js;


before_install:
  - npm i

script:
  - npm test

notifications:
  email:
    recipients:
      - ksreddy9945@gmail.com
  on_success: change
  on_failure: always
